version: "3.7"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    volumes:
      - postgres1-1:/postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_sample_dev # or use phoenix_sample_test, depending on MIX_ENV

volumes:
  postgres1-1:
